name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # ensure linter & test runner are available
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          flake8 src tests

      - name: Run pytest
        run: |
          # this will create ci_reports/results.xml
          pytest --junitxml=ci_reports/results.xml --maxfail=1 --disable-warnings -q

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: ci_reports/results.xml
